# Site settings
title: Kyle Frick's Portfolio
description: Kyle Frick's Portfolio
favicon: /assets/img/avatar.jpg
# baseurl: https://themrfrick.github.io
# url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-141674035-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Kyle Frick
  title: Computer Scientist
  address: Bay City, Texas
  email: themrfrick@gmail.com
  link: 
  weibo:
  github: themrfrick
  linkedin: themrfrick
  twitter: themrfrick
  gavatar: /assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Rutgers University
      location: New Brunswick, New Jersey
      title: Office of Information Consultant 
      started: 2018
      duration: (2018 - Present)
      description: Rutgers Office of Information Technology aids the Rutgers populous with technical troubleshooting of internal networks, software, hardware and printing services. I assist patrons with issues such as internet connectivity, printing, and general computer issues. I am certified in Residential Network Dispatch, Level 1 Help Desk, Labs Consultant and currently a Level 2 Consultant in Training. I am responsible for network troubleshooting through dispatch and walk-in appointments for labs and help desk, and primarily responsible for over the phone troubleshooting with the Rutgers populous.
    - work2:
      company: Federation of Workers and Employers of America
      location: Bay City, Texas
      title: IT Specialist
      started: 2016
      duration: (2016 - 2017)
      description: Federation of Workers and Employers of America (FEWA) is a non-profit company that aids in the H2-A and H2-B process with their clientele. During my time with FEWA I maintained the health of a single server with 20 computers attached to the infrastructure, repaired and forged new APEX functions for their Salesforce Environment. I also aided in the transition from the Classic Salesforce environment to the Lightning Salesforce environment. I primarily used Node.JS, HTML/CSS, Java and APEX to build and adjust these applications.
    - work3:
      company: Chegg 
      location: Online
      title: Tutor
      started: 2015
      duration: (2015 - 2017)
      description: Chegg is an online tutoring and general help site for high school and college students. As a tutor I designed personalized tutoring schedules with 76 students. Tutoring sessions were either a one-time session or weekly sessions. I tutored students in Computer Science, Mathematics (Calculus II and below), Physics, Chemistry, and Spanish. 
  educationHistory:
    - education1:
      organization: Rutgers University 
      location: New Brunswick, New Jersey
      degree: Bachelor's of Science
      major: Computer Science
      started: 2017
      duration: (2017 - 2019)
      description: Graduated in August 2019
    - education2: 
      organization: Wentworth Institute of Technology
      location: Boston, Massachussetts
      degree: Bachelor's of Science
      major: Computer Science
      started: 2015
      duration: (2015 - 2016)
      description:
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Spanish
      proficiency: Intermediate
    - language3:
      name: Japanese
      proficiency: Limit
    - language4:
      name: Korean
      proficiency: Limit
    - language5: 
      name: Italian
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Java (Advanced)
      percentage: 100%
    - skill2:
      name: HTML5/CSS3 (Intermediate)
      percentage: 90%
    - skill3:
      name: JavaScript (Intermediate)
      percentage: 75%
    - skill8:
      name: C++ (Intermediate)
      percentage: 75%
    - skill9: 
      name: C (Intermediate)
      percentage: 75%
    - skill4:
      name: Node.js (Adept)
      percentage: 70%
    - skill5:
      name: Python (Adept)
      percentage: 60%
    - skill6: 
      name: SQL (Adept)
      percentage: 50%
    - skill7:
      name: Golang (Adept)
      percentage: 50%
    
  Projects:
    - project2:
      name: Chess - Android Port
      created: 2019
      languages: Android, Java 8
      description: Chess is a board game in which two players compete to take down the other player's king piece by moving and overtaking the board with their other pieces. This specific project is a port of my console version of the game. This version has added on top of it additional error checking and the ability to save and watch replays of previously saved games. 
      link:
      type: School Project - Software Methodology
    - project3:
      name: Chess - Console Port 
      languages: Java 8
      created: 2019
      description: Chess is a board game in which two players compete to take down the other player's king piece by moving and overtaking the board with their other pieces. This project has since been ported to an Android application, but it runs perfectly fine otherwise. The program starts up with White's turn and prompts the user for a move using the row-rank of the piece and the destination that the user desires.
      link: 
      type: School Project - Software Methodology
    - project4: 
      name: Photo Library
      languages: JavaFX, Java 8
      created: 2019
      description: The photo library allows users to view, add/edit descriptions and tag the photos displayed within it. The photo library is a consistent program that serializes the information of the photos within it. The photos are not stored within the program itself, but the location of where the photo is on the system is stored, therefore if a photo is added to the program and moved to a new location within the file system, it will no longer appear within the program.
      link:
      type: School Project - Software Methodology
    - project5: 
      name: Song Library
      languages: JavaFX, Java 8
      created: 2019
      description: The song library holds the information of various songs that are imported into it and sorts them by Song Title and then by Author. The song library is consistent and stores the information into a JSON file. The song library is unable to play any of the songs that are put into it. 
      link: 
      type: School Project - Software Methodology
    - project1:
      name: To-Do/Task Manager
      created: 2016
      languages: Node.js, Ejs, Bootstrap, CSS, Semantic.ui 
      description: The to-do/task manager is a simple task manager that keeps track of incomplete, in process and completed tasks. The tasks can be sorted by urgency and alphabetically. This was created during my time at FEWA and had been connected to their emailing system for internal emailing of when new tasks were created, when a task was being worked on, and created weekly reports of all the tickets in a .pdf file. 
      link:
      type: Work Project - FEWA
    - project6:
      name: Dungeons and Dragons 5th Edition Character Creator
      created: 2015
      languages: JavaFX, Java, C++
      description: Ever feel as though creating a new character for playing or world building takes time? Time that you may not have? Well, look no further! Use this 5th Edition character creator to stream-line character creation! The program is fully programed in JavaFX using Java with an original console version being coded in C++. 
      link:
      type: School Project - Computer Science II (C++ and Java)
    
      
